-- Runs once, automatically, the first time the postgres container's data
-- volume is created (see docker-entrypoint-initdb.d in the official
-- postgres image, and how this file is mounted in ../../docker-compose.yml).
--
-- Why this exists: every migration in src/migrations/*.ts hardcodes the
-- schema name "erp_test" into its raw SQL (CREATE TABLE "erp_test"."x", ...)
-- instead of running unqualified against whatever schema TypeORM is
-- configured for. That schema has to exist before migrationsRun kicks in on
-- backend boot, or every migration fails with `schema "erp_test" does not
-- exist`. See PLAN.md step 0.16 for the follow-up decision on whether to
-- rename this to "public" -- not done here because it's unknown whether any
-- already-deployed environment has this migration applied under a specific
-- schema, and rewriting migration history blind to that is how you get a
-- database that can't agree with itself.
CREATE SCHEMA IF NOT EXISTS erp_test;
